original_format_superset_keys = {
    'contributors',
    'coordinates',
    'created_at',
    'display_text_range',
    'entities hashtags',
    'entities media',
    'entities polls',
    'entities symbols',
    'entities urls',
    'entities user_mentions',
    'extended_entities media',
    'extended_tweet display_text_range',
    'extended_tweet entities hashtags',
    'extended_tweet entities media',
    'extended_tweet entities symbols',
    'extended_tweet entities urls',
    'extended_tweet entities user_mentions',
    'extended_tweet extended_entities media',
    'extended_tweet full_text',
    'favorite_count',
    'favorited',
    'filter_level',
    'geo',
    'id',
    'id_str',
    'in_reply_to_screen_name',
    'in_reply_to_status_id',
    'in_reply_to_status_id_str',
    'in_reply_to_user_id',
    'in_reply_to_user_id_str',
    'is_quote_status',
    'lang',
    'matching_rules',
    'place',
    'place bounding_box coordinates',
    'place bounding_box type',
    'place country',
    'place country_code',
    'place full_name',
    'place id',
    'place name',
    'place place_type',
    'place url',
    'possibly_sensitive',
    'quote_count',
    'quoted_status contributors',
    'quoted_status coordinates',
    'quoted_status created_at',
    'quoted_status display_text_range',
    'quoted_status entities hashtags',
    'quoted_status entities symbols',
    'quoted_status entities urls',
    'quoted_status entities user_mentions',
    'quoted_status extended_tweet display_text_range',
    'quoted_status extended_tweet entities hashtags',
    'quoted_status extended_tweet entities media',
    'quoted_status extended_tweet entities symbols',
    'quoted_status extended_tweet entities urls',
    'quoted_status extended_tweet entities user_mentions',
    'quoted_status extended_tweet extended_entities media',
    'quoted_status extended_tweet full_text',
    'quoted_status favorite_count',
    'quoted_status favorited',
    'quoted_status filter_level',
    'quoted_status geo',
    'quoted_status id',
    'quoted_status id_str',
    'quoted_status in_reply_to_screen_name',
    'quoted_status in_reply_to_status_id',
    'quoted_status in_reply_to_status_id_str',
    'quoted_status in_reply_to_user_id',
    'quoted_status in_reply_to_user_id_str',
    'quoted_status is_quote_status',
    'quoted_status lang',
    'quoted_status place',
    'quoted_status place bounding_box coordinates',
    'quoted_status place bounding_box type',
    'quoted_status place country',
    'quoted_status place country_code',
    'quoted_status place full_name',
    'quoted_status place id',
    'quoted_status place name',
    'quoted_status place place_type',
    'quoted_status place url',
    'quoted_status possibly_sensitive',
    'quoted_status quote_count',
    'quoted_status quoted_status_id',
    'quoted_status quoted_status_id_str',
    'quoted_status reply_count',
    'quoted_status retweet_count',
    'quoted_status retweeted',
    'quoted_status source',
    'quoted_status text',
    'quoted_status truncated',
    'quoted_status user contributors_enabled',
    'quoted_status user created_at',
    'quoted_status user default_profile',
    'quoted_status user default_profile_image',
    'quoted_status user description',
    'quoted_status user favourites_count',
    'quoted_status user follow_request_sent',
    'quoted_status user followers_count',
    'quoted_status user following',
    'quoted_status user friends_count',
    'quoted_status user geo_enabled',
    'quoted_status user id',
    'quoted_status user id_str',
    'quoted_status user is_translator',
    'quoted_status user lang',
    'quoted_status user listed_count',
    'quoted_status user location',
    'quoted_status user name',
    'quoted_status user notifications',
    'quoted_status user profile_background_color',
    'quoted_status user profile_background_image_url',
    'quoted_status user profile_background_image_url_https',
    'quoted_status user profile_background_tile',
    'quoted_status user profile_banner_url',
    'quoted_status user profile_image_url',
    'quoted_status user profile_image_url_https',
    'quoted_status user profile_link_color',
    'quoted_status user profile_sidebar_border_color',
    'quoted_status user profile_sidebar_fill_color',
    'quoted_status user profile_text_color',
    'quoted_status user profile_use_background_image',
    'quoted_status user protected',
    'quoted_status user screen_name',
    'quoted_status user statuses_count',
    'quoted_status user time_zone',
    'quoted_status user translator_type',
    'quoted_status user url',
    'quoted_status user utc_offset',
    'quoted_status user verified',
    'quoted_status_id',
    'quoted_status_id_str',
    'reply_count',
    'retweet_count',
    'retweeted',
    'retweeted_status contributors',
    'retweeted_status coordinates',
    'retweeted_status created_at',
    'retweeted_status display_text_range',
    'retweeted_status entities hashtags',
    'retweeted_status entities symbols',
    'retweeted_status entities urls',
    'retweeted_status entities user_mentions',
    'retweeted_status extended_tweet display_text_range',
    'retweeted_status extended_tweet entities hashtags',
    'retweeted_status extended_tweet entities media',
    'retweeted_status extended_tweet entities symbols',
    'retweeted_status extended_tweet entities urls',
    'retweeted_status extended_tweet entities user_mentions',
    'retweeted_status extended_tweet extended_entities media',
    'retweeted_status extended_tweet full_text',
    'retweeted_status favorite_count',
    'retweeted_status favorited',
    'retweeted_status filter_level',
    'retweeted_status geo',
    'retweeted_status id',
    'retweeted_status id_str',
    'retweeted_status in_reply_to_screen_name',
    'retweeted_status in_reply_to_status_id',
    'retweeted_status in_reply_to_status_id_str',
    'retweeted_status in_reply_to_user_id',
    'retweeted_status in_reply_to_user_id_str',
    'retweeted_status is_quote_status',
    'retweeted_status lang',
    'retweeted_status place bounding_box coordinates',
    'retweeted_status place bounding_box type',
    'retweeted_status place country',
    'retweeted_status place country_code',
    'retweeted_status place full_name',
    'retweeted_status place id',
    'retweeted_status place name',
    'retweeted_status place place_type',
    'retweeted_status place url',
    'retweeted_status possibly_sensitive',
    'retweeted_status quote_count',
    'retweeted_status reply_count',
    'retweeted_status retweet_count',
    'retweeted_status retweeted',
    'retweeted_status source',
    'retweeted_status text',
    'retweeted_status truncated',
    'retweeted_status user contributors_enabled',
    'retweeted_status user created_at',
    'retweeted_status user default_profile',
    'retweeted_status user default_profile_image',
    'retweeted_status user description',
    'retweeted_status user favourites_count',
    'retweeted_status user follow_request_sent',
    'retweeted_status user followers_count',
    'retweeted_status user following',
    'retweeted_status user friends_count',
    'retweeted_status user geo_enabled',
    'retweeted_status user id',
    'retweeted_status user id_str',
    'retweeted_status user is_translator',
    'retweeted_status user lang',
    'retweeted_status user listed_count',
    'retweeted_status user location',
    'retweeted_status user name',
    'retweeted_status user notifications',
    'retweeted_status user profile_background_color',
    'retweeted_status user profile_background_image_url',
    'retweeted_status user profile_background_image_url_https',
    'retweeted_status user profile_background_tile',
    'retweeted_status user profile_banner_url',
    'retweeted_status user profile_image_url',
    'retweeted_status user profile_image_url_https',
    'retweeted_status user profile_link_color',
    'retweeted_status user profile_sidebar_border_color',
    'retweeted_status user profile_sidebar_fill_color',
    'retweeted_status user profile_text_color',
    'retweeted_status user profile_use_background_image',
    'retweeted_status user protected',
    'retweeted_status user screen_name',
    'retweeted_status user statuses_count',
    'retweeted_status user time_zone',
    'retweeted_status user translator_type',
    'retweeted_status user url',
    'retweeted_status user utc_offset',
    'retweeted_status user verified',
    'source',
    'text',
    'truncated',
    'user contributors_enabled',
    'user created_at',
    'user default_profile',
    'user default_profile_image',
    'user derived klout influence_topics',
    'user derived klout interest_topics',
    'user derived klout profile_url',
    'user derived klout score',
    'user derived klout user_id',
    'user description',
    'user favourites_count',
    'user follow_request_sent',
    'user followers_count',
    'user following',
    'user friends_count',
    'user geo_enabled',
    'user id',
    'user id_str',
    'user is_translator',
    'user lang',
    'user listed_count',
    'user location',
    'user name',
    'user notifications',
    'user profile_background_color',
    'user profile_background_image_url',
    'user profile_background_image_url_https',
    'user profile_background_tile',
    'user profile_image_url',
    'user profile_image_url_https',
    'user profile_link_color',
    'user profile_sidebar_border_color',
    'user profile_sidebar_fill_color',
    'user profile_text_color',
    'user profile_use_background_image',
    'user protected',
    'user screen_name',
    'user statuses_count',
    'user time_zone',
    'user translator_type',
    'user url',
    'user utc_offset',
    'user verified',
    'scopes followers', #no idea what the hell this key is
    'geo', 
    'coordinates',
    'retweeted_status place', 
    'user profile_banner_url', 
    'retweeted_status extended_entities media', 
    'retweeted_status entities media', 
    'user derived locations',
    'retweeted_status quoted_status in_reply_to_status_id_str',
    'retweeted_status quoted_status user default_profile',
    'retweeted_status quoted_status user profile_background_color',
    'retweeted_status quoted_status truncated',
    'retweeted_status quoted_status user profile_background_image_url',
    'retweeted_status quoted_status user followers_count',
    'retweeted_status quoted_status user id',
    'retweeted_status quoted_status_id',
    'retweeted_status quoted_status lang',
    'retweeted_status quoted_status in_reply_to_user_id',
    'retweeted_status quoted_status user protected',
    'retweeted_status quoted_status user profile_use_background_image',
    'retweeted_status quoted_status user profile_image_url',
    'retweeted_status quoted_status user is_translator',
    'retweeted_status quoted_status text',
    'retweeted_status quoted_status in_reply_to_status_id',
    'retweeted_status quoted_status id',
    'retweeted_status quoted_status user favourites_count',
    'retweeted_status quoted_status coordinates',
    'retweeted_status quoted_status user description',
    'retweeted_status quoted_status source',
    'retweeted_status quoted_status user profile_image_url_https',
    'retweeted_status quoted_status contributors',
    'retweeted_status quoted_status user follow_request_sent',
    'retweeted_status quoted_status created_at',
    'retweeted_status quoted_status entities user_mentions',
    'retweeted_status quoted_status user profile_sidebar_fill_color',
    'retweeted_status quoted_status quote_count',
    'retweeted_status quoted_status user following',
    'retweeted_status quoted_status user profile_banner_url',
    'retweeted_status quoted_status reply_count',
    'retweeted_status quoted_status user name',
    'retweeted_status quoted_status user profile_background_image_url_https',
    'retweeted_status quoted_status entities symbols',
    'retweeted_status quoted_status retweet_count',
    'retweeted_status quoted_status user id_str',
    'retweeted_status quoted_status retweeted',
    'retweeted_status quoted_status user created_at',
    'retweeted_status quoted_status place',
    'retweeted_status quoted_status user friends_count',
    'retweeted_status quoted_status user location',
    'retweeted_status quoted_status user listed_count',
    'retweeted_status quoted_status is_quote_status',
    'retweeted_status quoted_status in_reply_to_user_id_str',
    'retweeted_status quoted_status_id_str',
    'retweeted_status quoted_status user screen_name',
    'retweeted_status quoted_status user profile_sidebar_border_color',
    'retweeted_status quoted_status user default_profile_image',
    'retweeted_status quoted_status user utc_offset',
    'retweeted_status quoted_status favorited',
    'retweeted_status quoted_status user verified',
    'retweeted_status quoted_status user profile_background_tile',
    'retweeted_status quoted_status user translator_type',
    'retweeted_status quoted_status user profile_text_color',
    'retweeted_status quoted_status in_reply_to_screen_name',
    'retweeted_status quoted_status user notifications',
    'retweeted_status quoted_status user url',
    'retweeted_status quoted_status id_str',
    'retweeted_status quoted_status entities hashtags',
    'retweeted_status quoted_status favorite_count',
    'retweeted_status quoted_status geo',
    'retweeted_status quoted_status user lang',
    'retweeted_status quoted_status user geo_enabled',
    'retweeted_status quoted_status user profile_link_color',
    'retweeted_status quoted_status filter_level',
    'retweeted_status quoted_status user contributors_enabled',
    'retweeted_status quoted_status entities urls',
    'retweeted_status quoted_status user statuses_count',
    'retweeted_status quoted_status user time_zone',
    'quoted_status entities media',
    'retweeted_status quoted_status entities media',
    'retweeted_status quoted_status display_text_range',
    'retweeted_status quoted_status extended_entities media',
    'quoted_status extended_entities media',
    'retweeted_status quoted_status possibly_sensitive',
    'user derived klout influence_topics',
    'user derived klout user_id',
    'user derived klout profile_url',
    'user derived klout interest_topics',
    'user derived klout score',
    'retweeted_status quoted_status place country',
    'retweeted_status quoted_status place url',
    'retweeted_status quoted_status place full_name',
    'retweeted_status quoted_status extended_tweet entities urls',
    'retweeted_status quoted_status extended_tweet entities symbols',
    'retweeted_status quoted_status extended_tweet entities hashtags',
    'retweeted_status quoted_status extended_tweet full_text',
    'retweeted_status quoted_status place id',
    'retweeted_status quoted_status place name',
    'retweeted_status quoted_status extended_tweet display_text_range',
    'retweeted_status quoted_status extended_tweet extended_entities media',
    'retweeted_status quoted_status extended_tweet entities media',
    'retweeted_status quoted_status extended_tweet entities user_mentions',
    'retweeted_status quoted_status place bounding_box coordinates',
    'retweeted_status quoted_status place bounding_box type',
    'retweeted_status quoted_status place place_type',
    'retweeted_status quoted_status place country_code',
    'coordinates type',
    'geo type',
    'coordinates coordinates',
    'geo coordinates',
    'retweeted_status scopes followers',
    'retweeted_status coordinates type', 
    'retweeted_status geo type', 
    'retweeted_status coordinates coordinates',
    'retweeted_status geo coordinates',
    'retweeted_status entities polls',
    'retweeted_status quoted_status quoted_status_id',
    'retweeted_status quoted_status quoted_status_id_str',
    'quoted_status entities polls',
    'retweeted_status quoted_status entities polls',
    'quoted_status coordinates coordinates', 
    'quoted_status geo coordinates', 
    'quoted_status geo type', 
    'quoted_status coordinates type',
    'quoted_status user withheld_in_countries', 
    'retweeted_status quoted_status user withheld_in_countries', 
    'retweeted_status quoted_status withheld_in_countries', 
    'quoted_status withheld_in_countries',
    'quoted_status scopes followers'
    }

original_format_minimum_set_keys = {
    'contributors',
    'created_at',
    'entities hashtags',
    'entities symbols',
    'entities urls',
    'entities user_mentions',
    'favorite_count',
    'favorited',
    'filter_level',
    'id',
    'id_str',
    'in_reply_to_screen_name',
    'in_reply_to_status_id',
    'in_reply_to_status_id_str',
    'in_reply_to_user_id',
    'in_reply_to_user_id_str',
    'is_quote_status',
    'lang',
    'matching_rules',
    'quote_count',
    'reply_count',
    'retweet_count',
    'retweeted',
    'source',
    'text',
    'truncated',
    'user contributors_enabled',
    'user created_at',
    'user default_profile',
    'user default_profile_image',
    'user description',
    'user favourites_count',
    'user follow_request_sent',
    'user followers_count',
    'user following',
    'user friends_count',
    'user geo_enabled',
    'user id',
    'user id_str',
    'user is_translator',
    'user lang',
    'user listed_count',
    'user location',
    'user name',
    'user notifications',
    'user profile_background_color',
    'user profile_background_image_url',
    'user profile_background_image_url_https',
    'user profile_background_tile',
    'user profile_image_url',
    'user profile_image_url_https',
    'user profile_link_color',
    'user profile_sidebar_border_color',
    'user profile_sidebar_fill_color',
    'user profile_text_color',
    'user profile_use_background_image',
    'user protected',
    'user screen_name',
    'user statuses_count',
    'user time_zone',
    'user translator_type',
    'user url',
    'user utc_offset',
    'user verified'}


activity_streams_superset_keys = {
    'actor displayName',
    'actor favoritesCount',
    'actor followersCount',
    'actor friendsCount',
    'actor id',
    'actor image',
    'actor languages',
    'actor link',
    'actor links',
    'actor listedCount',
    'actor objectType',
    'actor postedTime',
    'actor preferredUsername',
    'actor statusesCount',
    'actor summary',
    'actor twitterTimeZone',
    'actor utcOffset',
    'actor verified',
    'body',
    'display_text_range',
    'favoritesCount',
    'generator displayName',
    'generator link',
    'gnip klout_profile klout_user_id',
    'gnip klout_profile link',
    'gnip klout_profile topics',
    'gnip klout_score',
    'gnip matching_rules',
    'gnip urls',
    'id',
    'inReplyTo link',
    'link',
    'location country_code',
    'location displayName',
    'location geo coordinates',
    'location geo type',
    'location link',
    'location name',
    'location objectType',
    'location twitter_country_code',
    'location twitter_place_type',
    'long_object body',
    'long_object display_text_range',
    'long_object twitter_entities hashtags',
    'long_object twitter_entities media',
    'long_object twitter_entities symbols',
    'long_object twitter_entities urls',
    'long_object twitter_entities user_mentions',
    'long_object twitter_extended_entities media',
    'object actor displayName',
    'object actor favoritesCount',
    'object actor followersCount',
    'object actor friendsCount',
    'object actor id',
    'object actor image',
    'object actor languages',
    'object actor link',
    'object actor links',
    'object actor listedCount',
    'object actor location displayName',
    'object actor location objectType',
    'object actor objectType',
    'object actor postedTime',
    'object actor preferredUsername',
    'object actor statusesCount',
    'object actor summary',
    'object actor twitterTimeZone',
    'object actor utcOffset',
    'object actor verified',
    'object body',
    'object display_text_range',
    'object favoritesCount',
    'object generator displayName',
    'object generator link',
    'object id',
    'object inReplyTo link',
    'object link',
    'object location country_code',
    'object location displayName',
    'object location geo coordinates',
    'object location geo type',
    'object location link',
    'object location name',
    'object location objectType',
    'object location twitter_country_code',
    'object location twitter_place_type',
    'object long_object body',
    'object long_object display_text_range',
    'object long_object twitter_entities hashtags',
    'object long_object twitter_entities media',
    'object long_object twitter_entities symbols',
    'object long_object twitter_entities urls',
    'object long_object twitter_entities user_mentions',
    'object long_object twitter_extended_entities media',
    'object object id',
    'object object link',
    'object object objectType',
    'object object postedTime',
    'object object summary',
    'object objectType',
    'object postedTime',
    'object provider displayName',
    'object provider link',
    'object provider objectType',
    'object summary',
    'object twitter_entities hashtags',
    'object twitter_entities symbols',
    'object twitter_entities urls',
    'object twitter_entities user_mentions',
    'object twitter_filter_level',
    'object twitter_lang',
    'object verb',
    'objectType',
    'postedTime',
    'provider displayName',
    'provider link',
    'provider objectType',
    'retweetCount',
    'twitter_entities hashtags',
    'twitter_entities media',
    'twitter_entities symbols',
    'twitter_entities urls',
    'twitter_entities user_mentions',
    'twitter_extended_entities media',
    'twitter_filter_level',
    'twitter_lang',
    'twitter_quoted_status actor displayName',
    'twitter_quoted_status actor favoritesCount',
    'twitter_quoted_status actor followersCount',
    'twitter_quoted_status actor friendsCount',
    'twitter_quoted_status actor id',
    'twitter_quoted_status actor image',
    'twitter_quoted_status actor languages',
    'twitter_quoted_status actor link',
    'twitter_quoted_status actor links',
    'twitter_quoted_status actor listedCount',
    'twitter_quoted_status actor location displayName',
    'twitter_quoted_status actor location objectType',
    'twitter_quoted_status actor objectType',
    'twitter_quoted_status actor postedTime',
    'twitter_quoted_status actor preferredUsername',
    'twitter_quoted_status actor statusesCount',
    'twitter_quoted_status actor summary',
    'twitter_quoted_status actor twitterTimeZone',
    'twitter_quoted_status actor utcOffset',
    'twitter_quoted_status actor verified',
    'twitter_quoted_status body',
    'twitter_quoted_status display_text_range',
    'twitter_quoted_status favoritesCount',
    'twitter_quoted_status generator displayName',
    'twitter_quoted_status generator link',
    'twitter_quoted_status id',
    'twitter_quoted_status inReplyTo link',
    'twitter_quoted_status link',
    'twitter_quoted_status location country_code',
    'twitter_quoted_status location displayName',
    'twitter_quoted_status location geo coordinates',
    'twitter_quoted_status location geo type',
    'twitter_quoted_status location link',
    'twitter_quoted_status location name',
    'twitter_quoted_status location objectType',
    'twitter_quoted_status location twitter_country_code',
    'twitter_quoted_status location twitter_place_type',
    'twitter_quoted_status long_object body',
    'twitter_quoted_status long_object display_text_range',
    'twitter_quoted_status long_object twitter_entities hashtags',
    'twitter_quoted_status long_object twitter_entities media',
    'twitter_quoted_status long_object twitter_entities symbols',
    'twitter_quoted_status long_object twitter_entities urls',
    'twitter_quoted_status long_object twitter_entities user_mentions',
    'twitter_quoted_status long_object twitter_extended_entities media',
    'twitter_quoted_status object id',
    'twitter_quoted_status object link',
    'twitter_quoted_status object objectType',
    'twitter_quoted_status object postedTime',
    'twitter_quoted_status object summary',
    'twitter_quoted_status objectType',
    'twitter_quoted_status postedTime',
    'twitter_quoted_status provider displayName',
    'twitter_quoted_status provider link',
    'twitter_quoted_status provider objectType',
    'twitter_quoted_status twitter_entities hashtags',
    'twitter_quoted_status twitter_entities symbols',
    'twitter_quoted_status twitter_entities urls',
    'twitter_quoted_status twitter_entities user_mentions',
    'twitter_quoted_status twitter_filter_level',
    'twitter_quoted_status twitter_lang',
    'twitter_quoted_status verb',
    'verb',
    'object twitter_entities media',
    'object twitter_extended_entities media',
    'actor location displayName',
    'gnip profileLocations',
    'actor location objectType',
    'geo coordinates',
    'geo type',
    'twitter_quoted_status twitter_entities media',
    'twitter_quoted_status twitter_extended_entities media',
    'object geo coordinates',
    'object geo type'}

activity_streams_minimum_set_keys = {
    'actor displayName',
    'actor favoritesCount',
    'actor followersCount',
    'actor friendsCount',
    'actor id',
    'actor image',
    'actor languages',
    'actor link',
    'actor links',
    'actor listedCount',
    'actor objectType',
    'actor postedTime',
    'actor preferredUsername',
    'actor statusesCount',
    'actor summary',
    'actor twitterTimeZone',
    'actor utcOffset',
    'actor verified',
    'body',
    'favoritesCount',
    'generator displayName',
    'generator link',
    'gnip matching_rules',
    'id',
    'link',
    'object id',
    'object link',
    'object objectType',
    'object postedTime',
    'objectType',
    'postedTime',
    'provider displayName',
    'provider link',
    'provider objectType',
    'retweetCount',
    'twitter_entities hashtags',
    'twitter_entities symbols',
    'twitter_entities urls',
    'twitter_entities user_mentions',
    'twitter_filter_level',
    'twitter_lang',
    'verb'}

